version: 2

# 在构建前执行的命令
before:
  hooks:
    - go mod tidy

# 构建配置
builds:
  - id: apkhub
    main: .
    binary: apkhub
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # 自动注入版本信息
    ldflags:
      - -s -w
      - -X github.com/apkhub/apkhub-cli/internal/version.Version={{.Version}}
      - -X github.com/apkhub/apkhub-cli/internal/version.Commit={{.Commit}}
      - -X github.com/apkhub/apkhub-cli/internal/version.BuildDate={{.Date}}

# 打包配置
archives:
  - id: default
    # 文件名格式：apkhub-v1.0.0-linux-amd64.tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # 默认使用 tar.gz
    formats: ['tar.gz']
    # Windows 平台使用 zip
    format_overrides:
      - goos: windows
        formats: ['zip']
    
# 生成校验和文件
checksum:
  name_template: 'SHA256SUMS.txt'

# GitHub Release 配置
release:
  # Release 标题
  name_template: "ApkHub CLI {{.Version}}"
  # 不创建草稿
  draft: false
  # 自动生成 release notes
  mode: append
  header: |
    ## ApkHub CLI {{.Version}}
    
    ### Installation
    
    #### Linux/macOS
    ```bash
    # Download the appropriate archive for your system
    curl -L https://github.com/apkhub/apkhub-cli/releases/download/{{.Tag}}/{{ .ProjectName }}-{{.Version}}-linux-x86_64.tar.gz -o apkhub.tar.gz
    
    # Extract
    tar xzf apkhub.tar.gz
    
    # Move to PATH
    sudo mv apkhub /usr/local/bin/
    
    # Make executable
    sudo chmod +x /usr/local/bin/apkhub
    ```
    
    #### Windows
    Download the Windows archive and extract `apkhub.exe` to a directory in your PATH.

# 自动生成的 changelog
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999