name: Release with GoReleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: ~> 2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          SCOOP_BUCKET_GITHUB_TOKEN: ${{ secrets.SCOOP_BUCKET_GITHUB_TOKEN }}

      - name: Update Scoop Bucket
        if: success()
        run: |
          # 获取版本号（去掉 v 前缀）
          VERSION="${{ github.ref_name }}"
          VERSION_NO_V="${VERSION#v}"
          
          # 获取发布信息
          RELEASE_DATA=$(curl -s "https://api.github.com/repos/huanfeng/apkhub-cli/releases/tags/${VERSION}")
          
          # 下载 SHA256SUMS.txt 获取哈希值
          curl -sL "https://github.com/huanfeng/apkhub-cli/releases/download/${VERSION}/SHA256SUMS.txt" > /tmp/checksums.txt
          
          # 提取各架构的哈希值（注意文件名包含 cli）
          HASH_64=$(grep "apkhub-cli-${VERSION_NO_V}-windows-x86_64.zip" /tmp/checksums.txt | cut -d' ' -f1)
          HASH_ARM64=$(grep "apkhub-cli-${VERSION_NO_V}-windows-arm64.zip" /tmp/checksums.txt | cut -d' ' -f1)
          
          # 克隆 Scoop bucket 仓库
          git clone https://x-access-token:${{ secrets.SCOOP_BUCKET_GITHUB_TOKEN }}@github.com/huanfeng/apkhub-scoop-bucket.git /tmp/scoop-bucket
          cd /tmp/scoop-bucket
          
          # 配置 git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # 更新 manifest
          cat > bucket/apkhub.json << EOF
          {
              "version": "${VERSION_NO_V}",
              "description": "A command-line tool for managing distributed APK repositories",
              "homepage": "https://github.com/huanfeng/apkhub-cli",
              "license": "MIT",
              "architecture": {
                  "64bit": {
                      "url": "https://github.com/huanfeng/apkhub-cli/releases/download/${VERSION}/apkhub-cli-${VERSION_NO_V}-windows-x86_64.zip",
                      "hash": "${HASH_64}"
                  },
                  "arm64": {
                      "url": "https://github.com/huanfeng/apkhub-cli/releases/download/${VERSION}/apkhub-cli-${VERSION_NO_V}-windows-arm64.zip",
                      "hash": "${HASH_ARM64}"
                  }
              },
              "bin": "apkhub.exe",
              "checkver": {
                  "github": "https://github.com/huanfeng/apkhub-cli"
              },
              "autoupdate": {
                  "architecture": {
                      "64bit": {
                          "url": "https://github.com/huanfeng/apkhub-cli/releases/download/v\$version/apkhub-cli-\$version-windows-x86_64.zip"
                      },
                      "arm64": {
                          "url": "https://github.com/huanfeng/apkhub-cli/releases/download/v\$version/apkhub-cli-\$version-windows-arm64.zip"
                      }
                  },
                  "hash": {
                      "url": "https://github.com/huanfeng/apkhub-cli/releases/download/v\$version/SHA256SUMS.txt"
                  }
              }
          }
          EOF
          
          # 提交更改
          git add bucket/apkhub.json
          if ! git diff --cached --quiet; then
            git commit -m "Update apkhub to version ${VERSION_NO_V}"
            git push origin master
            echo "Successfully updated Scoop bucket to version ${VERSION_NO_V}"
          else
            echo "No changes to commit"
          fi